{
    "CreateLinks": [],
    "OnFailure": "/internalApp/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/internalApp/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "docsID": "#Page:Docs_Create/#Control:docsID/#Value",
        "internalUserId": "#Page:Docs_Create/#Control:internalUserId/#Value",
        "fileName": "#Page:Docs_Create/#Control:fileName/#Value",
        "filePath": "#Page:Docs_Create/#Control:filePath/#Value",
        "fileHash": "#Page:Docs_Create/#Control:fileHash/#Value",
        "uploadedAt": "#Page:Docs_Create/#Control:uploadedAt/#Value",
        "isDeleted": "#Page:Docs_Create/#Control:isDeleted/#Value"
    },
    "Target": {
        "EntitySet": "Docs",
        "Service": "/internalApp/Services/sapProjectSrv.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}